<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LP-000873.local" failures="1" tests="7" name="com.qa.crm2.tests.LoginPageTest" time="11.459" errors="0" timestamp="2025-07-25T11:37:01 IST" skipped="3">
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="forgotPwdLinkExistTest" time="0.554"/>
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageUrlTest" time="0.056"/>
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginTest" time="2.432"/>
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="2.082">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="2.107">
    <failure message="=====PAGE TITLE NOT FOUND===== expected [Account Login1] but found [Account Login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: =====PAGE TITLE NOT FOUND===== expected [Account Login1] but found [Account Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.qa.crm2.tests.LoginPageTest.loginPageTitleTest(LoginPageTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="2.135">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.qa.crm2.tests.LoginPageTest" name="loginPageTitleTest" time="2.093">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
</testsuite> <!-- com.qa.crm2.tests.LoginPageTest -->
